# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uzo < Formula
  desc ""
  homepage "https://github.com/marzelwidmer/uzo"
  version "1.0.1"

  on_macos do
    url "https://github.com/marzelwidmer/uzo/releases/download/1.0.1/uzo_1.0.1_darwin_all.tar.gz"
    sha256 "47145fbe0b886278759496ab45ec71988c22a1f3393ca3a873fabcfddd7f5756"

    def install
      bin.install "uzo"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marzelwidmer/uzo/releases/download/1.0.1/uzo_1.0.1_linux_amd64.tar.gz"
        sha256 "a36f9fb45f630eebc8e3e2e87d8e66d21ef4c6ee2a7e27dc70533b01eb58c43f"

        def install
          bin.install "uzo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marzelwidmer/uzo/releases/download/1.0.1/uzo_1.0.1_linux_arm64.tar.gz"
        sha256 "e65316cc21b84e9cadefbed43044ecb05e60bd74119c65d36f6ed65e3c42869a"

        def install
          bin.install "uzo"
        end
      end
    end
  end
end
