# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uzo < Formula
  desc ""
  homepage "https://github.com/marzelwidmer/uzo"
  version "0.0.0"

  on_macos do
    url "https://github.com/marzelwidmer/uzo/releases/download/0.0.0/uzo_0.0.0_darwin_all.tar.gz"
    sha256 "a34d9c7ad4f309622b548dc928b7a04da9d93e8b1bddff45524190979cc11bea"

    def install
      bin.install "uzo"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marzelwidmer/uzo/releases/download/0.0.0/uzo_0.0.0_linux_amd64.tar.gz"
        sha256 "6363f1b8091e4c388d2f47f4c6eb8dd4e65b4115dd7d059a66ea3680c018ead8"

        def install
          bin.install "uzo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marzelwidmer/uzo/releases/download/0.0.0/uzo_0.0.0_linux_arm64.tar.gz"
        sha256 "a80d4b841137c977ddfea489af65876c416aa2e1e8b9275c06909f860b5855f1"

        def install
          bin.install "uzo"
        end
      end
    end
  end
end
